name: Sanity Checks

on: [push, pull_request]

jobs:
    compute-graph:
        name: Compute graph
        runs-on: ubuntu-24.04
        steps:
          - name: Install prerequisites
            run: |
                sudo apt-get install jq
                sudo pip3 install setuptools
                sudo pip3 install xbstrap y4
          - name: Prepare directories
            run: |
                mkdir src/
                mkdir build/
          - name: Checkout
            uses: actions/checkout@v2
            with:
              path: src/
          - name: Compute xbstrap-pipeline graph
            run: |
                set -x
                cp ../src/ci/pipeline.yml .
                echo '{"pkg_management": {"format": "xbps"}}' > bootstrap-site.yml
                xbstrap init ../src
                xbstrap rolling-versions fetch
                xbstrap rolling-versions determine --json | jq '{"commits":map_values({"rolling_id":.})}' > new-bootstrap-commits.yml
                # Ensure that the previs xbstrap command does not see bootstrap-commits.yml
                # until the file is fully written.
                mv new-bootstrap-commits.yml ../src/bootstrap-commits.yml
                xbstrap-pipeline compute-graph --artifact
            working-directory: build/
